### ISSUE TITLE
ファイル指定時のリターンコードが正しく動作していない

### ISSUE THREAD

**Issue by gsparkskyknight** [yumetodo/utf8_to_windows31j_cvt_checker#1]
# 現状の動作
- パイプ入力時
  - iconvに失敗する行がない場合にリターンコード0を返す
  - iconvに失敗する行がある場合にリターンコード1を返す
- ファイル指定時
  - iconvに失敗する行がない場合にリターンコード1を返す
  - iconvに失敗する行がある場合にリターンコード0を返す

# 期待する動作
- パイプ入力時
  - iconvに失敗する行がない場合にリターンコード0を返す
  - iconvに失敗する行がある場合にリターンコード1を返す
- ファイル指定時
  - iconvに失敗する行がない場合にリターンコード0を返す
  - iconvに失敗する行がある場合にリターンコード1を返す

# 問題となるコード
https://github.com/yumetodo/utf8_to_windows31j_cvt_checker/blob/382360215f7ad83c02e232a63c93934aa19e87e3/src/utf8_to_windows31j_cvt_checker.cpp#L35-L40

**Comment by yumetodo** [comment]
#3, #4 で解決しました

**Comment by gsparkskyknight** [comment]
修正確認しました。
