### ISSUE TITLE
変換に失敗した行数の表示が1行ずれている

### ISSUE THREAD

**Issue by gsparkskyknight** [yumetodo/utf8_to_windows31j_cvt_checker#2]
# 要望内容
変換に失敗した行数の表示が0オリジンであり、実際の行数と1行ずれている。
行数の表示を1オリジンにすることで実際の行数と合うようになり、実行結果からよりスムーズにエラー行を特定できるようになると思われる。

# 現状の動作
[sample.csv](https://github.com/yumetodo/utf8_to_windows31j_cvt_checker/files/7297265/sample.csv)
を対象に`utf8_to_windows31j_cvt_checker`を実行した時、変換に失敗した行数の表示が[0,1,2,3]となる。

# 期待する動作
[sample.csv](https://github.com/yumetodo/utf8_to_windows31j_cvt_checker/files/7297265/sample.csv)
を対象に`utf8_to_windows31j_cvt_checker`を実行した時、変換に失敗した行数の表示が[1,2,3,4]となる。

**Comment by yumetodo** [comment]
#7 にて修正しました

**Comment by gsparkskyknight** [comment]
修正確認しました。
